website:
  name: 网站名称
  domain: www.yujie.com
  msg: 我这是一个博客网站
spring:
  profiles:
    active: test
  thymeleaf:
    mode: LEGACYHTML5
  #  mongodb
  data:
    mongodb:
      database: test
      port: 27017
      host: 192.168.1.18
  datasource:
    url: jdbc:mysql://localhost:3306/demo?&useSSL=false
    password: yujie
    username: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 200
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 100
      max-idle: 10
      max-wait: 100000
    timeout: 0
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.yujie.model
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
##mongo配置
#server:
#  port: 8082
#  context-path: /boot